name: Deploy F1A

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Create Service Account
        run: |
          echo '${{ secrets.F1A_FIREBASE_SERVICE_ACCOUNT }}' > service-account.json

      - name: Validate firebase.json
        run: |
          test -f firebase.json

      - name: Deploy F1A
        env:
          GOOGLE_APPLICATION_CREDENTIALS: service-account.json
        run: |
          firebase deploy \
            --only hosting:sitef1a \
            --project projeto-ceocard