name: Deploy F1A

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.F1A_FIREBASE_SERVICE_ACCOUNT }}'
          create_credentials_file: true
          export_environment_variables: true

      # Instala uma versão estável do Firebase CLI
      - name: Install Firebase CLI
        run: |
          npm install -g firebase-tools@13.35.1

      - name: Show Versions
        run: |
          node -v
          npm -v
          firebase --version

      - name: Verify Credentials
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS"
          ls -lah "$GOOGLE_APPLICATION_CREDENTIALS"

      - name: Deploy Hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          firebase deploy \
            --project projeto-ceocard \
            --only hosting:sitef1a \
            --non-interactive \
            --debug